### ISSUE TITLE
rookie question

### ISSUE THREAD

**Issue by bennybetch** [nikshepsvn/instacart-delivery-availability-check#5]
hey guys - thanks for doing this.
Quick q: i did rename the file to credentials.json, but am getting the following error.

 File "check.py", line 12, in <module>
    credentials = json.load(open("credentials.json"))
FileNotFoundError: [Errno 2] No such file or directory: 'credentials.json'

**Comment by nikshepsvn** [comment]
Hmm, are you sure that the file is called `credentials.json` and in the same directory as `check.py`? can you paste a screenshot of your directory with the files

**Comment by bennybetch** [comment]
![Capture](https://user-images.githubusercontent.com/62563654/79492875-a0816500-7fee-11ea-9c70-f62f9dc44c4b.JPG)

**Comment by nikshepsvn** [comment]
Hm, and can you share the exact command you are using to execute `check.py`?

**Comment by bennybetch** [comment]
C:\Users\benbe\Documents\instacartyay\instacart-delivery-availability-check-master>python check.py
Traceback (most recent call last):
  File "check.py", line 12, in <module>
    credentials = json.load(open("credentials.json"))
FileNotFoundError: [Errno 2] No such file or directory: 'credentials.json'

**Comment by nikshepsvn** [comment]
hm weird, I think it might be some weird python path problem. Do me a favour and replace 

`json.load(open("credentials.json"))` 

 in the code with 

`json.load(open("C:\Users\benbe\Documents\instacartyay\instacart-delivery-availability-check-master\credentials.json"))`

and run it again

**Comment by bennybetch** [comment]
awesome, that worked with an r before the path, much appreciated
